### ISSUE TITLE
Create a leaderboard

### ISSUE THREAD

**Issue by Centoller** [GiantQuartz/SkyBlock#188]
add an island top (if it's better floating text) that measures the blocks placed or the size of the island

**Comment by GiantQuartz** [comment]
This project would have to use SQLite instead of JSON to implement that feature correctly. That implies breaking backwards compatibility, plus pmmp does not include the php sqlite extension by default.

If pmmp binaries ever include the SQLite extension, I might create a workaround to implement this, until then, it's not an option.
